package com.oalam.servlets.basis;

import java.io.*;
// l'extension java  pour la gestion des servlets   
// !! au "x" de javax. cela precise que c'est un extension de Java   
import javax.servlet.*;
import javax.servlet.annotation.WebServlet;

@WebServlet(name = "ReallySimpleServlet", urlPatterns = {"/ReallySimpleServlet"})
public class ReallySimple extends GenericServlet {

    @Override
    public void service(ServletRequest req, ServletResponse res)
            throws ServletException, IOException {
        // Recherche du flux d'ecriture   
        ServletOutputStream out = res.getOutputStream();

        // Ecriture de la page reponse   
        out.println("<HTML><HEAD>");
        out.println("<TITLE>hello_1.java</TITLE>");
        out.println("</HEAD>");
        out.println("<BODY>");

        out.println("<H3>Hello World...</H3>");
        out.println("<BR>Page generated by hello_1.java");

        out.println("</BODY></HTML>");
    }

    @Override
    public String getServletInfo() {
        return "JavaSide sample : servlet hello_1";
    }
}
